this ( -- t)
fork ( fn -- t)
join ( t -- )
kill ( t -- )
send ( x1..xn n t --)
receive ( -- r1..rn)
?receive ( m -- [r1..rn true] or [m false])
spawn func ( x1..xn n -- m)
sync ( m -- r1..rn)
